<B> Write a function so that the columns of the output matrix are powers of the input
vector</B>  

The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1

In [20]:
import numpy as np
x = np.array([1, 2, 4, 5])
N = 3
np.vander(x, N)


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [15]:
def vander_Input(x,N,order):
    X=x.size
    #result_array=np.empty((N,X),dtype=int)
    result_array=np.zeros((N,X),dtype=int)
    #result_array=x.reshape(1,x.shape[0]).transpose()
       # arr_T=inp_arr.reshape(1,inp_arr.shape[0]).transpose()
    if order.upper()=="TRUE":
        for i in range(N):
            power_vector=np.array(np.power(x,i))
            result_array[i]=power_vector
    else:
        for i in range(N-1,-1,-1):
            power_vector=np.array(np.power(x,i))
            result_array[(N-1)-i]=power_vector
    return result_array

In [18]:
import numpy as np
print('Generate a Vandermonde matrix...')

N=int(input('Enter the value of N power :'))

print('Enter comma separated list of elements eg. 1,2,3 :')
input_vector=input()
input_list=list(map(int,input_vector.split(',')))
x=np.array(input_list)
print('Input vector is :')
print(x)

order=input("Enter 'True' for increasing order of powers else enter 'False' :")

result_array=vander_Input(x,N,order)
print('The resultant Vandermonde matrix is :')
print(result_array.T)

Generate a Vandermonde matrix...
Enter the value of N power :3
Enter comma separated list of elements eg. 1,2,3 :
1,2,4,5
Input vector is :
[1 2 4 5]
Enter 'True' for increasing order of powers else enter 'False' :True
The resultant Vandermonde matrix is :
[[ 1  1  1]
 [ 1  2  4]
 [ 1  4 16]
 [ 1  5 25]]


In [13]:
import numpy as np
x = np.array([1, 2, 4, 5])
N = 3
#np.vander(x, N)
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [16,  4,  1],
       [25,  5,  1]], dtype=int32)